#!/usr/bin/env nu
# Reports the alert detail (compact markdown table) for a kunai NGSOTI file.
# The file is passed via the FILE env var.
# Usage: FILE=logs/ngsoti/<hash>/kunai.jsonl.gz nu ngsoti_detail.nu
#
# Two outputs:
#  - live console display of the alerts (with colors),
#  - markdown file written into logs/ngsoti/scanresult<TS>/<descriptive>.md (in
#    the logs directory). The file is named from the detected detection
#    families (family+count) preceded by the short hash of the sample.
#    The common TS of a whole run is passed by the SCAN_TS env var
#    (set by the wrapper); otherwise generated here.
use kunai_detect_compromise.nu *

let file = $env.FILE
# Common timestamp of the scan session (provided by the wrapper to group all
# samples in the same scanresult<TS> folder).
let ts = ($env.SCAN_TS? | default (date now | format date "%Y%m%d_%H%M%S"))
# max number of lines displayed per family; beyond, only the count is shown
let max_rows = 25

# Materializes the file ONCE in an in-memory DataFrame (polars collect, without
# into-nu). Each detection then filters this DataFrame in RAM instead of
# re-unrolling the build_base plan (open + unnests) for each family. This avoids
# re-scanning the hundreds of thousands of rows x 9 times and saturating
# the CPU load (the plugin parallelized each re-collect on all cores).
let base = (build_base $file 200000 | polars collect)

let fams = {
  execve:        {|b| detect_execve $b}
  file_create:   {|b| detect_file_create $b}
  connect:       {|b| detect_connect $b}
  send_data:     {|b| detect_send_data $b}
  dns_query:     {|b| detect_dns_query $b}
  kill:          {|b| detect_kill $b}
  bpf_prog_load: {|b| detect_bpf $b}
  mmap_exec:     {|b| detect_mmap_exec $b}
  prctl:         {|b| detect_prctl $b}
}

# Markdown buffer of the final report (.md file output).
mut md_lines = [ $"# Alert detail — ($file)" "" ]

# Number of alerts per detection family (for the output file name).
mut fam_counts = {}

print $"(ansi cyan)###### File: ($file)(ansi reset)"
for fam in ($fams | columns) {
  # We stay in polars as long as possible: counts are never materialized in
  # nushell (shape = [rows, columns], light), and we convert to nushell (into-nu)
  # only the first max_rows rows. Avoids blowing up memory/CPU for massive
  # families (e.g. send_data at 300k+ rows).
  let fam_frame = (do (($fams | get $fam)) $base)
  let shape = ($fam_frame | polars shape | polars into-nu)
  let n = ($shape.0.rows | into int)
  $fam_counts = ($fam_counts | insert $fam $n)
  print $"(ansi green)== ($fam) — ($n) alerts(ansi reset)"
  $md_lines = ($md_lines | append $"## ($fam) — ($n) alerts" "")
  if $n > 0 {
    let l2 = ($fam_frame | polars first $max_rows | polars collect | polars into-nu)
    let more = if $n > $max_rows { $n - $max_rows } else { 0 }
    if $n <= $max_rows {
      print ($l2 | to md)
      $md_lines = ($md_lines | append (($l2 | to md) | split row "\n"))
    } else {
      print ($l2 | to md)
      $md_lines = ($md_lines | append (($l2 | to md) | split row "\n"))
      print $"(ansi yellow)… and ($more) more alerts not shown(ansi reset)"
      $md_lines = ($md_lines | append $"… and ($more) more alerts not shown")
    }
  }
  print ""
  $md_lines = ($md_lines | append "")
}

# Consolidated summary (IP/ports and download URLs): generated by the
# report_bilan procedure of kunai_detect_compromise.nu and appended at the end
# of the report.
let bilan = (report_bilan $base 50)
$md_lines = ($md_lines | append $bilan)

# Writes the markdown report in the logs directory, under
# logs/ngsoti/scanresult<TS>/<name>.md. The log path is derived from the input
# file (e.g. logs/ngsoti/<hash>/kunai.jsonl.gz → logs folder of the input).
let log_dir = ($file | path dirname | path dirname)
let out_dir = ($log_dir | path join $"scanresult($ts)")
mkdir $out_dir
# File name: delegated to the report_basename procedure of
# kunai_detect_compromise.nu (descriptive name from the detected families).
let hash = ($file | path dirname | path basename)
let out_file = ($out_dir | path join $"(report_basename $hash $fam_counts).md")
$md_lines | str join "\n" | save --force $out_file
print $"(ansi cyan)Markdown report written: ($out_file)(ansi reset)"
